This is makeindex, version 2.15 [TeX Live 2016] (kpathsea + Thai support).
Scanning style file /Users/maxi/WORKSPACE/WIP/bachelorarbeit-microgrid-modellierung/text/.texpadtmp/cluster_microgrid_v1.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/maxi/WORKSPACE/WIP/bachelorarbeit-microgrid-modellierung/text/.texpadtmp/cluster_microgrid_v1.acn....done (2 entries accepted, 0 rejected).
Sorting entries....done (2 comparisons).
Generating output file /Users/maxi/WORKSPACE/WIP/bachelorarbeit-microgrid-modellierung/text/.texpadtmp/cluster_microgrid_v1.acr....done (9 lines written, 0 warnings).
Output written in /Users/maxi/WORKSPACE/WIP/bachelorarbeit-microgrid-modellierung/text/.texpadtmp/cluster_microgrid_v1.acr.
Transcript written in /Users/maxi/WORKSPACE/WIP/bachelorarbeit-microgrid-modellierung/text/.texpadtmp/cluster_microgrid_v1.alg.
